version: '3'
services:
  back:
    build: 
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
    - hangman
  front:
    build: 
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "8081:3000"
    networks:
    - hangman

networks:
  hangman:
