const LOG_TYPE = {
  RECEIVED: "RECEIVED",
  SENT: "SENT",
  ERROR: "ERROR",
}

const BACK_MESSAGE_TYPE = {
  INIT_GAME: "B_INIT_GAME",
  INIT_PLAYER: "B_INIT_PLAYER",
  GAME_READY: "B_GAME_READY",
  NEXT_ROUND: "B_NEXT_ROUND",
  GUESS: "B_GUESS",
  ERROR: "ERROR",
}

const FRONT_MESSAGE_TYPE = {
  INIT_GAME: "F_INIT_GAME",
  JOIN_GAME: "F_JOIN_GAME",
  SUBMIT_GUESS: "F_SUBMIT_GUESS",
}

module.exports = {
  LOG_TYPE,
  BACK_MESSAGE_TYPE,
  FRONT_MESSAGE_TYPE,
}
