const LOG_TYPE = {
  RECEIVED: "RECEIVED",
  SENT: "SENT",
  ERROR: "ERROR",
}

const BACK_MESSAGE_TYPE = {
  INIT_GAME: "B_INIT_GAME",
  GAME_READY: "B_GAME_READY",
  ERROR: "ERROR",
}

const FRONT_MESSAGE_TYPE = {
  INIT_GAME: "F_INIT_GAME",
  JOIN_GAME: "F_JOIN_GAME",
}

module.exports = {
  LOG_TYPE,
  BACK_MESSAGE_TYPE,
  FRONT_MESSAGE_TYPE,
}
